### ISSUE TITLE
AOI 추가 방법 개선

### ISSUE THREAD

**Issue by hyungjungkim** [hyungjungkim/vision-based-status-monitoring-for-legacy-HMI#1]
AOI editor를 기반으로 AOI 선택과 threshold 설정, OCR test 기능을 통합하고자 합니다.

**Comment by MondaySHB** [comment]
AOI Add를 위한 kem_studio_add_aoi.ui 를 새로 구성하여 동작하도록 했고 push 하겠습니다.
이전 aoi_editor.ui는 삭제 가능합니다.

**Comment by hyungjungkim** [comment]
Retry 기능과 OCR test 활성화까지 감동입니다!!! 다이얼로그 사이즈가 좀 큰 감이 있어 조정하면서 좀 더 테스트해보고 close할게요. 감사합니다!

**Comment by hyungjungkim** [comment]
테스트 후 size 수정 사항 commit 및 추가 수정 사항을 notion에 업데이트 했습니다. 확인 후 수정 바랍니다.
