### ISSUE TITLE
카메라가 없는 컴퓨터 실행 시 오류

### ISSUE THREAD

**Issue by hyungjungkim** [hyungjungkim/vision-based-status-monitoring-for-legacy-HMI#2]
Raspberry Pi에서 테스트를 하다가 Add AOI class에서 카메라가 없는 컴퓨터에서 오류가 발생하는 것을 확인하였습니다. cv2 코드가 카메라를 사용하지 않는 옵션 중에도 실행이 되도록 되어 있어 이 부분에 대해 정리 바랍니다.

**Comment by MondaySHB** [comment]
넵 교수님 
확인 결과
cv2가 camera를 사용하지 않을 때에도 image load 등에 사용되기 때문에
필요할 것으로 예상됩니다.
카메라를 사용하지 않더라도 cv2 install은 필수 일 것 같습니다.

**Comment by MondaySHB** [comment]
add AOI 부분을 추가적으로 확인해보겠습니다

**Comment by MondaySHB** [comment]
수정하여 push 했습니다.
오류가 해결되었을지 
카메라 없는 새 pc로 확인했으나 
확신이 없어 확인을 부탁드립니다.
감사합니다.

**Comment by hyungjungkim** [comment]
카메라가 없는 컴퓨터에서도 작동하는 것을 확인했습니다. 수고하셨습니다!
