### ISSUE TITLE
옵션 설정값 로딩 조건 개선

### ISSUE THREAD

**Issue by hyungjungkim** [hyungjungkim/vision-based-status-monitoring-for-legacy-HMI#3]
옵션 변경 후 재실행 시, 옵션 메뉴를 실행하지 않으면 기본값으로 작동하는 오류 해결이 필요합니다.

**Comment by MondaySHB** [comment]
option 세팅하는 위치를 수정하여 push하였습니다.
감사합니다.

**Comment by hyungjungkim** [comment]
option 값이 저장되나, 프로그램을 재시작하면 초기화되어 저장된 값이 반영되지 않습니다. 확인 바랍니다.

**Comment by MondaySHB** [comment]
수정하여 push 했습니다!

**Comment by hyungjungkim** [comment]
확인했습니다. 잘 되네요!
