### ISSUE TITLE
네트워크 카메라 연결 방법 추가

### ISSUE THREAD

**Issue by hyungjungkim** [hyungjungkim/vision-based-status-monitoring-for-legacy-HMI#4]
http://... 형태의 네트워크 카메라 주소를 이용한 카메라 접속이 가능하도록 옵션과 기능 추가가 필요합니다.

**Comment by hyungjungkim** [comment]
@MondaySHB 옵션 내의 파라미터 구분이 필요할 것 같은데요. index와 url을 하나의 변수로 하고 형식을 확인할까요? 아니면 명시적으로 옵션을 모두 저장(index 사용 여부, index 값, url 사용 여부, url 값)해서 관리하는게 좋을까요? 의견 부탁합니다(이메일 내용의 연장).

**Comment by hyungjungkim** [comment]
@MondaySHB IP camera 설정 gui 업데이트 하였습니다. 설정 기능과 연결 진행 바랍니다.

**Comment by MondaySHB** [comment]
@hyungjungkim 넵 교수님 요청사항 반영하여 수정하였습니다.
감사합니다.

**Comment by hyungjungkim** [comment]
@MondaySHB 확인하였고, option global variable 추가가 필요해서 수정하였습니다. 감사합니다!
