### ISSUE TITLE
Add AOI segmentation fault in Linux

### ISSUE THREAD

**Issue by MondaySHB** [hyungjungkim/vision-based-status-monitoring-for-legacy-HMI#6]
Add AOI를 할 때 linux에서 segmentation fault가 발생하는 것을 확인했습니다.
이를 수정을 할 예정이나 시간이 조금 소요될 예정입니다.

**Comment by MondaySHB** [comment]
리눅스에서 segmentaiton fault의 원인이 addAOI 창을 닫을 때 발생하는 것을 확인하였고
간헐적으로 일어나는 것으로 보아 process 간의 race condition이 발생하는 것으로 추정됩니다.
우선 Linux에서는 AOI 지역 직사각형을 설정 했을 때 닫히지 않고 직접 닫기 버튼을 누르는 방식으로
변경하면 문제가 없습니다.

**Comment by MondaySHB** [comment]
이에 따라 Windows에서만 닫히도록 설정했습니다.

**Comment by hyungjungkim** [comment]
넵.
